### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by mrabhishek** [bramp/objectgraph#5]
Is this class thread safe?

**Comment by bramp** [comment]
No. Calling traverse from multiple thread would be bad.

**Comment by mrabhishek** [comment]
Thanks for the quick answer. At this point it' more like a code review -

A method like the one below is thread safe though - is that correct?  As long as each thread gets a new ObjectGraph object - it should be safe?

```
private void updateObject(final Object data) {
        ObjectGraph
                .visitor((object, clazz) -> {
                    // do something  with data.
                    return false;
                })
                .excludeStatic()
                .excludeTransient()
                .excludeClasses()
                .traverse(data);
    }
```

**Comment by bramp** [comment]
Yes that's totally fine. As long as each thread gets a different ObjectGraph object

**Comment by mrabhishek** [comment]
wow! so quick! thank you!
